%STARTUP - script that runs when Matlab starts!
%
% NJS (TUoS) 2022

%% Set-up paths independent of OS
if ispc; userdir= getenv('USERPROFILE');
else; userdir= getenv('HOME');
end

% Github
disp('Loading NJS paths...');
base_string = strcat(userdir,filesep,'Documents',filesep,'github');
paths = {strcat(filesep,'philips-rawdata'),...
    strcat(filesep,'ge-rawdata',filesep,'read_mr_latest'),...
    strcat(filesep,'ge-rawdata',filesep,'orchestra-sdk-2.0-1.matlab'),...
    strcat(filesep,'ge-rawdata',filesep,'gw_coils_files'),...
    strcat(filesep,'ge-rawdata',filesep,'orchestra-sdk-2.0-1.matlab',filesep,'Scripts'),...
    strcat(filesep,'Matlab_MRI'),...
    strcat(filesep,'mns-research-pack'),...
    strcat(filesep,'zte-recon'),...
    strcat(filesep,'ute-zte-utilities'),...
    strcat(filesep,'matlab-schemer'),...
    strcat(filesep,'fasta-matlab'),...
    strcat(filesep,'fasta-matlab',filesep,'solvers'),...
    strcat(filesep,'tinycs'),...
    strcat(filesep,'gl-hosvd',filesep,'RiceOptVST'),...
    strcat(filesep,'pulmonary-MRI-reconstruction')
    };
for p = 1:length(paths)
    path = strcat(base_string,paths{p});
    if exist(path,'dir')
        addpath(genpath(path));
    end
end

% Matlab-Schemer
schemer_import(strcat(userdir,filesep,'Documents',filesep,'github',filesep,...
    'matlab-schemer',filesep,'schemes',filesep,'monokai.prf'));

% Gitlab
base_string = strcat(userdir,filesep,'Documents',filesep,'gitlab');
paths = {strcat(filesep,'tensor_toolbox'),...
    strcat(filesep,'plab')
    };
for p = 1:length(paths)
    path = strcat(base_string,paths{p});
    if exist(path,'dir')
        addpath(genpath(path));
    end
end

disp('Done...');
